language: node_js

node_js:
  - 10
  - 11
  - 12
  - 13

deploy:
  - provider: script
    skip_cleanup: true
    script: npm ci && npm run build && npx wrangler publish
    on:
      branch: cloudflare-workers
