name: Deploy

on:
  push:
    branches:
      - ark-50-update-wrangler-to-v2-in-client-deployment-flow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build
      - run: npm i wrangler@v3.22.3
      - run: CF_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }} CF_ZONE_ID=${{ secrets.CF_ZONE_ID }} CF_API_TOKEN=${{ secrets.CF_API_TOKEN }} npx wrangler publish
