name: Deploy

on:
  push:
    branches:
      - master
      - cloudflare-workers

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Install wrangler
        run: sudo npm i @cloudflare/wrangler -g
      - name: Use wrangler
        run: CF_API_TOKEN=${{ secrets.CF_API_TOKEN }} wrangler publish